table categories
	lineageTag: f0a5c805-6e97-442b-9dc8-eb68afc23042

	column CategoryID
		dataType: int64
		formatString: 0
		lineageTag: 667abd8b-2373-4ac0-b4da-cabac7c51329
		summarizeBy: none
		sourceColumn: CategoryID

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: bc5db8bf-7b66-480b-8d6e-dbde5bb70c26
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	partition categories = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NITHIS\OneDrive\Desktop\Grocery Sales Database\categories.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CategoryID", Int64.Type}, {"CategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

